color:
  lightness: 0.6551149968651857
  brandColors:
    - '#450003'
    - '#5C0002'
    - '#94090D'
    - '#D40D12'
    - '#FF1D23'
  saturation: 0.5216116338320104
  brandStrength: 0.6496777182094934
  rhythmicContrast: 0.09204746947904291
name: Food Art
layout_spectrum: 0.9189154610503465
typography_spectrum: 0.20291279000230134
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/cf06ef28-f163-488d-b028-f78fe9ff7d14.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/cf06ef28-f163-488d-b028-f78fe9ff7d14.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
title: Food Art Journey
description: >-
  Chefs are artist and create master pieces for us to enjoy. I am not a food
  critic, I am a honest food lover. My daughter and I share the same love for
  food. Thru this space we want to share our love for food. Welcome to our road
  trip of simple food art.
github: true
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/95302499-09d3-4320-a614-4e7eaf4f26fd.jpg
